baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "kepler 452b"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  location_link = "https://www.google.de/maps/place/52%C2%B033'20.3%22N+13%C2%B024'53.3%22E"
  resident_advisor_path = "http://www.residentadvisor.net/events/1003233"
  instagram_path = "http://www.instagram.com/kp452b/"
  facebook_path = "http://www.facebook.com/kepler452b.org"
